Join table
hasnatali1947/vet_clinic pull request #5
Opened 2023-06-08 17:34 UTC by hasnatali1947

**Did the following**

add some many-to-many relationships
created vets, specialization and visits table
Added data into tables
added queries to required questions

Screenshots:
![10](https://github.com/hasnatali1947/vet_clinic/assets/119807955/9e9af3fe-78ff-46fb-9a7b-41b7af96b975)

![11](https://github.com/hasnatali1947/vet_clinic/assets/119807955/2a7618be-c4ab-4a69-bd96-56d4a24dc8e2)
![12](https://github.com/hasnatali1947/vet_clinic/assets/119807955/c309414d-5f34-416f-adf7-a65eff2bf38a)
![13](https://github.com/hasnatali1947/vet_clinic/assets/119807955/713dfbd7-e2ac-4f2c-a627-18ddda505fb2)
![14](https://github.com/hasnatali1947/vet_clinic/assets/119807955/aabc3043-a528-41cc-94fc-e8ae567129ff)
![15](https://github.com/hasnatali1947/vet_clinic/assets/119807955/b7780553-ec63-40a5-b5d6-70984fccaa44)
![16](https://github.com/hasnatali1947/vet_clinic/assets/119807955/6c76115e-3df6-412d-ab25-1aa0e97218c7)
![17](https://github.com/hasnatali1947/vet_clinic/assets/119807955/4aec3199-b853-4dce-91bf-3f830cf9a222)
![18](https://github.com/hasnatali1947/vet_clinic/assets/119807955/ae89b0cf-5423-49fc-9bdd-61838af25595)

2023-06-08 18:11 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @hasnatali1947 , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  SQL Commands added in the correct files
:heavy_check_mark: Query results screenshots added to PR description
:heavy_check_mark: Use of correct Gitflow


There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 18:11 UTC, t-yanick commented on schema.sql
> +    id serial primary key,
- [ ] Great job working on this milestone. `specialization` is a join table which references two other tables to create a `many-to-many `relationship. Having a `primary key` of `id` is not actually necessary since the references are done with `foreign keys.` Kindly delete the id column.

2023-06-08 18:11 UTC, t-yanick commented on schema.sql
> +    id serial primary key,
- [ ] Great job working on this milestone. `visits` is a join table which references two other tables to create a `many-to-many `relationship. Having a `primary key` of `id` is not actually necessary since the references are done with `foreign keys.` Kindly delete the id column.

2023-06-08 18:11 UTC, t-yanick commented on queries.sql
> +limit 1;
- [ ] Great job adding query results to your PR description. At the moment, your PR is missing the screenshot of this query results. Kindly run this query and add the screenshot to the PR

2023-06-09 09:01 UTC, hasnatali1947 commented on queries.sql
> +limit 1;
![ss](https://github.com/hasnatali1947/vet_clinic/assets/119807955/0324af2e-9b58-45ca-bde1-5f7006c39732)

2023-06-09 09:15 UTC, hasnatali1947 commented on schema.sql
> +    id serial primary key,
![ss specialzation](https://github.com/hasnatali1947/vet_clinic/assets/119807955/6df977c4-2a3e-4b28-bc70-a571fb8c81a0)

2023-06-09 09:16 UTC, hasnatali1947 commented on schema.sql
> +    id serial primary key,
![Uploading ss visits.png…]()

2023-06-09 09:18 UTC, hasnatali1947 commented on queries.sql
> +limit 1;
![visits](https://github.com/hasnatali1947/vet_clinic/assets/119807955/25f094b5-c6e9-40c1-bcda-bfc4a1d3260b)

2023-06-09 09:19 UTC, hasnatali1947 commented on schema.sql
> +    id serial primary key,
![ss visits](https://github.com/hasnatali1947/vet_clinic/assets/119807955/a77e813d-d13b-4475-9a45-ae42080061c9)

2023-06-09 10:03 UTC, danmainah requested changes
Hi @hasnatali1947 , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  SQL commands added correctly using data.sql, queries.sql, and schema.sql files
✔️ Professional written README file with all sections required.

 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 10:03 UTC, danmainah commented on schema.sql
> +    id serial primary key,
- [ ] @hasnatali1947 Great work implementing the changes requested however you didn't make the changes in your schema.sql file, this is important as in the future you don't have to add the query to drop the id.

2023-06-09 10:03 UTC, danmainah commented on schema.sql
> +    id serial primary key,
- [ ] @hasnatali1947 Great work implementing the changes requested however you didn't make the changes in your schema.sql file, this is important as in the future you don't have to add the query to drop the id.

2023-06-09 10:57 UTC, cynthiainga approved these changes
Hi @hasnatali1947, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] All requested changes are implemented ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Query results screenshots are added to PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can get the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 10:59 UTC, merged